#!/usr/bin/env python3
"""Extract inline page styles, retokenize to craft system, write assets/pages.css."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "pages.css"

PAGES = [
    ("business.html", ".page-business"),
    ("about.html", ".page-about"),
    ("solutions.html", ".page-solutions"),
    ("licensing.html", ".page-licensing"),
]

REPLACEMENTS = [
    (r"rgba\(112,\s*150,\s*192,\s*\.28\)", "var(--border)"),
    (r"rgba\(112,\s*150,\s*192,\s*\.26\)", "var(--border)"),
    (r"rgba\(112,\s*150,\s*192,\s*\.25\)", "var(--border)"),
    (r"rgba\(112,\s*150,\s*192,\s*\.24\)", "var(--border-soft)"),
    (r"rgba\(112,\s*150,\s*192,\s*\.22\)", "var(--border-soft)"),
    (r"rgba\(112,\s*150,\s*192,\s*\.2\)", "var(--border-soft)"),
    (r"rgba\(112,\s*150,\s*192,\s*\.18\)", "var(--border-soft)"),
    (r"rgba\(112,\s*150,\s*192,\s*\.15\)", "var(--border-soft)"),
    (r"#79a9dd", "var(--accent)"),
    (r"#8fbaf4", "var(--accent)"),
    (r"#7199ca", "var(--accent-dim)"),
    (r"#a9caff", "var(--accent)"),
    (r"#e7ebf2", "var(--fg-2)"),
    (r"#e1e8f5", "var(--fg-2)"),
    (r"#cbd5e4", "var(--fg-2)"),
    (r"#d5dfef", "var(--fg-2)"),
    (r"#aebbd0", "var(--muted)"),
    (r"#dce8ff", "var(--fg-2)"),
    (r"#d6e4ff", "var(--fg-2)"),
    (r"#f0f3f8", "var(--fg)"),
    (r"#f3f5f8", "var(--fg)"),
    (r"#f5f7fb", "var(--fg)"),
    (r"#f0a36b", "var(--warn)"),
    (r"Roboto Mono,\s*monospace", "var(--font-mono)"),
    (r"Roboto Mono", "var(--font-mono)"),
    (r"var\(--text\)", "var(--fg)"),
    (r"var\(--blue\)", "var(--accent)"),
    (r"var\(--copper\)", "var(--warn)"),
    (r"backdrop-filter:\s*blur\([^)]+\);?", ""),
    (r"border-radius:\s*1\.2rem", "border-radius: 0"),
    (r"border-radius:\s*1\.25rem", "border-radius: 0"),
    (r"border-radius:\s*1\.15rem", "border-radius: 0"),
    (r"border-radius:\s*1rem", "border-radius: 0"),
    (r"box-shadow:\s*0\s+28px\s+70px[^;]+;", ""),
    (r"box-shadow:\s*0\s+30px\s+80px[^;]+;", ""),
    (r"background:\s*linear-gradient\(145deg,\s*rgba\(16,\s*26,\s*48[^;]+;", "background: var(--surface);"),
    (r"background:\s*linear-gradient\(145deg,\s*rgba\(18,\s*35,\s*58[^;]+;", "background: var(--surface);"),
    (r"background:\s*rgba\(18,\s*31,\s*57,\s*\.66\)", "background: var(--surface)"),
    (r"background:\s*rgba\(18,\s*31,\s*57,\s*\.42\)", "background: var(--surface)"),
    (r"#33445e", "var(--border)"),
    (
        r"linear-gradient\(90deg,rgba\(4,8,17,\.94\)[^)]+\),linear-gradient\(0deg,rgba\(4,8,17,\.82\)[^)]+\),",
        "linear-gradient(90deg,var(--hero-scrim-strong) 0%,var(--hero-scrim-mid) 38%,var(--hero-scrim-soft) 70%),linear-gradient(0deg,var(--hero-scrim-bottom) 0%,transparent 48%),",
    ),
]


def extract_style(html: str) -> str:
    m = re.search(r"<style>(.*?)</style>", html, re.DOTALL)
    return m.group(1).strip() if m else ""


def retokenize(css: str) -> str:
    for pattern, repl in REPLACEMENTS:
        css = re.sub(pattern, repl, css)
    css = re.sub(r"\n\s*\n\s*\n", "\n\n", css)
    return css


def main():
    chunks = [
        "/* Page-specific layouts — craft tokens from site.css */",
        "/* Generated by scripts/build-pages-css.py — do not hand-edit inline duplicates */",
        "",
    ]
    for filename, _ in PAGES:
        path = ROOT / filename
        if not path.exists():
            continue
        css = extract_style(path.read_text(encoding="utf-8"))
        if not css:
            continue
        chunks.append(f"/* --- {filename} --- */")
        chunks.append(retokenize(css))
        chunks.append("")
    OUT.write_text("\n".join(chunks), encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()