#!/usr/bin/env python3
"""OCR pitch deck slides and append to docs/site-copy-ocr.md."""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
OUT = ROOT / "docs" / "site-copy-ocr.md"
SLIDES = [
    ("slide-01-cover", "slide-01-cover.png"),
    ("slide-02-problem-statement", "slide-02-problem-statement.png"),
    ("slide-03-proposed-solution", "slide-03-proposed-solution.png"),
    ("slide-04-traction", "slide-04-traction.png"),
    ("slide-05-business-model", "slide-05-business-model.png"),
    ("slide-06-market-opportunity", "slide-06-market-opportunity.png"),
    ("slide-07-financials", "slide-07-financials.png"),
    ("slide-08-team", "slide-08-team-updated.png"),
    ("slide-09-competition", "slide-09-competition.png"),
    ("slide-10-current-funding-status", "slide-10-current-funding-status.png"),
    ("slide-11-summary", "slide-11-summary.png"),
]

FALLBACK = {
    "slide-04-traction": """**Headline:** Traction & Validation

**Proof points:** Discovery Sprint pilots underway; workflow automation prototypes in client environments; open-core Cortex releases on GitHub.

**Note:** Internal reference — do not publish investor metrics on marketing pages.""",
    "slide-05-business-model": """**Headline:** Business Model

**Commercial path:** Discovery Sprint → Pilot deployment → Production package.

**Pricing path (pilot phase):** $12K Discovery Sprint → $24K+ production engagement (figures subject to pilot validation).

**Revenue lanes:** Implementation services, commercial licensing, optional support retainer.""",
    "slide-08-team-updated": """**Headline:** Team

**@triphosphatedev** — Co-founder / engineering & platform architecture

**@ascendism** — Co-founder / product, operations & client delivery

**Note:** GitHub handles only on public site; roles from pitch deck OCR.""",
}


def ocr_image(path: Path) -> str:
    try:
        result = subprocess.run(
            ["tesseract", str(path), "stdout", "-l", "eng"],
            capture_output=True,
            text=True,
            timeout=120,
            check=True,
        )
        return result.stdout.strip()
    except (FileNotFoundError, subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return ""


def main() -> int:
    marker = "## Pitch deck slides (assets/slide-01–11)"
    existing = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if marker in existing:
        print("Pitch deck OCR section already present; skipping.")
        return 0

    sections = [marker, "", "_Auto-generated by scripts/ocr-slides.py_", ""]
    used_fallback = []

    for slug, filename in SLIDES:
        img = ASSETS / filename
        text = ocr_image(img) if img.exists() else ""
        if not text.strip():
            text = FALLBACK.get(slug, f"_(OCR unavailable for {filename})_")
            used_fallback.append(slug)
        sections.append(f"### {slug} — `assets/{filename}`")
        sections.append("")
        sections.append(text.strip())
        sections.append("")
        sections.append("---")
        sections.append("")

    if used_fallback:
        sections.append(f"_Fallback transcription used for: {', '.join(used_fallback)}_")
        sections.append("")

    block = "\n".join(sections)
    OUT.write_text(existing.rstrip() + "\n\n" + block + "\n", encoding="utf-8")
    print(f"Appended {len(SLIDES)} slide sections to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())